name: ela_me_olha_e_ve_um_bancuuuu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^3.0.1
  barcode_widget: ^2.0.3
  intl: ^0.17.0
  pdf: ^3.6.0
  printing: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para adicionar assets no futuro (imagens, ícones, etc), descomente:
  # assets:
  #   - images/logo.png
  #   - assets/

  # Para adicionar fontes personalizadas, use:
  # fonts:
  #   - family: NomeDaFonte
  #     fonts:
  #       - asset: fonts/NomeDaFonte-Regular.ttf
  #       - asset: fonts/NomeDaFonte-Bold.ttf
  #         weight: 700
